export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_OK = 'GET_TODOS_OK';
export const GET_TODOS_ERROR = 'GET_TODOS_ERROR';
